package Mitosis;

public enum ChromosomeIdentifier {
    CHROMOSOME_0,CHROMOSOME_1,CHROMOSOME_2,CHROMOSOME_3,CHROMOSOME_4,CHROMOSOME_5,CHROMOSOME_6,CHROMOSOME_7,CHROMOSOME_8,CHROMOSOME_9,CHROMOSOME_10,CHROMOSOME_11,CHROMOSOME_12,CHROMOSOME_13,CHROMOSOME_14,CHROMOSOME_15,CHROMOSOME_16,CHROMOSOME_17,CHROMOSOME_18,CHROMOSOME_19,CHROMOSOME_20,CHROMOSOME_22,CHROMOSOME_X,CHROMOSOME_Y
}
